- name: Install r1soft agent
  hosts: all
  become: yes
  become_method: sudo 


     
  tasks: 
  - name: Create a Repository
    copy:
      src: r1soft.repo
      dest: /etc/yum.repos.d/r1soft.repo
   
  - name: Install r1soft agent
    package:
      name: serverbackup-enterprise-agent 
      state: present
  
  - name: Start agent  
    command: /etc/init.d/cdp-agent start
       

  
  - name: Get key
    shell: "r1soft-setup --get-key http//3.84.5.130:8080"
    when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "6" 
    
  - name: Install kernel-devel
    yum:
      name: kernel-devel
      state: latest 
     
  
  - name: Get module
    shell: serverbackup-setup --get-module
    
  - name: Stop Iptables
    service: name=iptables state=stopped
  